version: "3.9"
services:
  code-quarkus-api:
    image: quay.io/quarkus/code-quarkus-api
    ports:
      - "8080:8080"
    env_file:
      - ./.envs/.env.internal
  code-quarkus-frontend:
    image: quay.io/app-sre/code-quarkus-int-build
    ports:
      - "3000:8082"
    depends_on:
      - code-quarkus-api