apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: code-quarkus-internal-build
spec:
  triggers:
    - type: "Generic"
      generic:
        secretReference:
          name: "code-quarkus-internal-build-secret"
        allowEnv: true
  source:
    type: Git
    git:
      uri: https://github.com/redhat-developer/code.quarkus.redhat.com
      ref: "internal"
    contextDir: code.quarkus.io
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.multistage
      buildArgs:
        - name: "MAVEN_BUILD_EXTRA_ARGS"
          value: "-Dno-app-running-test=true -Dquarkus.version=1.11.6.Final-redhat-00001 -Dquarkus.platform.version=1.11.6.Final-redhat-00001  -Pinternal-build -s maven-settings.xml"
        - name: "MAVEN_EXTRA_ARGS"
          value: "-Dmaven.settings=maven-settings.xml -Dinternal-build=true"
  output:
    to:
      kind: ImageStreamTag
      name: code-quarkus-internal:latest